# Generated by Django 5.2.4 on 2025-08-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
